//
//  Main.java
//
//  Generated by the Yava compiler v 0.0.0 on 10/28/2019.
//  All changes made to this file will be overwritten.
//

public class Main
{

    public static void main(String[] args)
    {
        start();
    }

    public static void println(String str)
    {
        System.out.println(str);
    }

    public static void println(int number)
    {
        System.out.println(number);
    }

    public static void println(float number)
    {
        System.out.println(number);
    }

    public static void println(double number)
    {
        System.out.println(number);
    }

    public static int add(int a, int b)
    {
        
        return a + b;
    }

    public static long add(long a, long b)
    {
        
        return a + b;
    }

    public static long add(long a, int b)
    {
        
        return a + b;
    }

    public static int multiply(int a, int b)
    {
        
        return a * b;
    }

    public static int divide(int a, int b)
    {
        
        return a / b;
    }

    public static int square(int a)
    {
        
        return a * a;
    }

    public static void sayHello()
    {
        println("Hello");
    }

    public static void fizzbuzz(int start, int stop)
    {
        
        for (int i = start; i  <= stop; i += 1)
        {
            
            if (i % 3 == 0 && i % 5 == 0)
            {
                println("Fizzbuzz");
            } 
            else if (i % 3 == 0)
            {
                println("Fizz");
            } 
            else if (i % 5 == 0)
            {
                println("Buzz");
            }
        }
    }

    public static void bottles()
    {
        
        for (int i = 99; i  >= 1; i -= 1)
        {
            
            if (i > 1)
            {
                int iMinusOne = i;
                iMinusOne--;
                println(i + " bottles of beer on the wall, " + i + " bottles of beer. Take one down and pass it around, " + iMinusOne + " bottles of beer on the wall.");
            } 
            else 
            {
                println("1 bottle of beer on the wall, 1 bottle of beer. Take one down and pass it around, no more bottles of beer on the wall.");
            }
        }
    }

    public static void foobar()
    {
        println("foobar");
    }

    public static int start()
    {
        println(1000000);
        println("hello\n    there.");
        int aaa = 1;
        int bbb = 2;
        int ccc = aaa + bbb;
        float fff = 1.0f;
        float ggg = fff + bbb;
        fizzbuzz(0, 100);
        bottles();
        sayHello();
        foobar();
        println("Hello world from " + "YavaTest.yava" + " on line #" + 44 + ", in function \"" + "start" + "\"");
        println("This was compiled with version " + "0.0.0" + " and build " + "12" + " of the Yava compiler.");
        println("This was compiled for the " + "Mac OS X" + " operating system.");
        int vr = 67;
        int intVar = 12;
        final long v = 36;
        float thisShouldBeAFloat = 3.6f;
        float thisShouldAlsoBeAFloat = 43.0f;
        double thisShouldBeADouble = 2.0;
        final int thisShouldBeAnInt = 312;
        boolean thisShouldBeABool = false;
        final String thisShouldBeAString = "I'm a string";
        char thisShouldBeAChar = 'c';
        vr = 68;
        
        {
            int thisShouldBeAnInt2 = 9;
        }
        int ll = add(2, 2);
        int x = 32;
        
        if (x != 0)
        {
            println("yo");
        } 
        else if (intVar == 12)
        {
            println("yo12");
        } 
        else if (v == 13)
        {
            println("yo13");
        } 
        else 
        {
            println("yo");
        }
        
        while (!(x-- == 0))
        {
            println(add(add(v + 2, 67 + intVar), x));
        }

        x = 0;
        println("x is " + x);
        
        do 
        {
            println(add(add(v + 2, 67 + intVar), x));
            x -= 1;
        } while (x == 0);

        println("Returning " + add(add(v + 2, 67 + intVar), 3));
                
        println("foo");
        println("bar");
        println("foo");
        println("bar");
        println("foo");
        println("bar");
        println("foo");
        println("bar");
        println("foo");
        println("bar");
        println("foo");
        println("bar");
        println("foo");
        println("bar");
        println("foo");
        println("bar");
        println("foo");
        println("bar");
        println("foo");
        println("bar");

        
        for (int k = 0; k < 20; ++k)
        {
            println("k is " + k);
        }
        
        for (int jk = 0; jk < 30; ++jk)
        {
            println("jk is " + jk);
        }
        
        for (int i = 1; i  <= 10; i += 1)
        {
            println("for");
        }
        
        for (int i = 10; i  >= 1; i -= 5)
        {
            println("rof");
        }
        
        for (int index = 10; index  >= 1; index -= 1)
        {
            println("hvað er þetta? " + index);
        }
        
        for (int j = 0; j  <= 20; j += 5)
        {
            println("hvað er þetta? " + j);
        }
        
        return add(add(intVar + 2, 67 + intVar), 3);
    }
}